### ISSUE TITLE
Android Contact Tracing API - zmiana zakresu projektu

### ISSUE THREAD

**Issue by borwoj** [ProteGO-Safe/android#100]
Apple i Google pracują nad systemem, który na pierwszy rzut oka w pełni pokrywa zakres projektu ProteGO. Rozważcie proszę, czy nie warto na ten moment wstrzymać się z budowaniem warstwy komunikacji i poczekać do maja, kiedy pierwsza wersja Android Contact Tracing API zostanie udostępniona.

Aplikacje tego typu mają sens wyłącznie wtedy, gdy są wykorzystywane na masową skalę. Wspomniane API zapewni Wam znacznie lepszą ekspozycję już teraz, a w przyszłości najprawdopodobniej będzie stałym elementem obu systemów operacyjnych.

Poza tym zwyczajnie dostarczy gotową abstrakcję i zdejmie z Was trochę roboty 🙂 

Więcej informacji:
- https://blog.google/inside-google/company-announcements/apple-and-google-partner-covid-19-contact-tracing-technology

- https://blog.google/documents/55/Android_Contact_Tracing_API.pdf

- https://blog.google/documents/58/Contact_Tracing_-_Bluetooth_Specification_v1.1_RYGZbKW.pdf

- https://blog.google/documents/56/Contact_Tracing_-_Cryptography_Specification.pdf

- https://www.theverge.com/2020/4/10/21216715/apple-google-coronavirus-covid-19-contact-tracing-app-details-use

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
