### ISSUE TITLE
Przycisk back i cofanie do historycznych aktywności

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#107]
Przycisk back naciskany w celu wyjścia z aplikacji, powoduje powrót do poprzednich historycznych aktywności które otwierałem. Lub np. jeśli kliknę 100 razy na "Porady" to żeby cofnąć się do poprzedniej aktywności z której przeszedłem muszę 100 razy kliknąć back. 
![Screenrecorder-2020-04-28-19-45-33-63](https://user-images.githubusercontent.com/26818304/80520491-c9f4a600-8989-11ea-9f44-fed719aea5c1.gif)
Xiaomi Mi 9, Android 10.

**Comment by matsobdev** [comment]
Dodatkowo w zakładce "Więcej" po wybraniu np. "Ustawienia" i kliknięciu cofnij (systemowy) cofa do "Home" (nie ma polskiego słowa?) a nie do list zakładki "Więcej", tak jakby ustawienia wyświetlały się zmianą układu (layout) a nie za sprawą nowej aktywności. Może do okna głównego aplikacji pasowała by "tabbed activity"?

Plus w regulaminie urządzenie definiowanie jako Android 6.0 i więcej. Zgoda na warunki, jako zaznaczenie checkboxa??!

**Comment by olekstomek** [comment]
@matsobdev Wydaje mi się że każda uwaga to powinien być osobny issues. 
Cofnięcie z ustawień przez systemowy back czy przez opcję "Powrót" u góry cofa nie zawsze do 'Home", zależy z którego miejsca wchodzisz w ustawienia. Bo jeśli np. z "Porady" trafisz właśnie w to miejsce a nie do "Home".

**Comment by matsobdev** [comment]
> @matsobdev Wydaje mi się że każda uwaga to powinien być osobny issues.
> Cofnięcie z ustawień przez systemowy back czy przez opcję "Powrót" u góry cofa nie zawsze do 'Home", zależy z którego miejsca wchodzisz w ustawienia. Bo jeśli np. z "Porady" trafisz właśnie w to miejsce a nie do "Home".

Może się zapędziłem i uogólniłem, ale nie zmienia to faktu, że coś tam jest nie halo, chociaż to psuje tylko estetykę. Ok, nie chciałem śmiecić, ale dla porządku będzie oddzielny issue dla kolejnych uwag.

**Comment by Tarvald** [comment]
@olekstomek 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-826

**Comment by olekstomek** [comment]
Częściowo opisany problem przeze mnie został rozwiązany. Klikanie wielokrotnie na ten sam element tworzy jego jedną aktywność. Ale jeśli ktoś będzie chodził po różnych activity aplikacji, np. 100x na przemian Home <-> Porady i będzie próbował zamknąć przez "back" aplikację to będzie musiał 100x "odklikać".

**Comment by olekstomek** [comment]
Release 4.5.0 (#155) rozwiązuje opisany tutaj przeze mnie problem. Działa OK.

Co do uwag @matsobdev:
> Dodatkowo w zakładce "Więcej" po wybraniu np. "Ustawienia" i kliknięciu cofnij (systemowy) cofa do "Home" (nie ma polskiego słowa?) a nie do list zakładki "Więcej", tak jakby ustawienia wyświetlały się zmianą układu (layout) a nie za sprawą nowej aktywności. Może do okna głównego aplikacji pasowała by "tabbed activity"?

Obecnie po wejściu w "Więcej" -> "Ustawienia" i cofnięciu back lub przez "Powrót" w lewej górnej części aplikacji nie wracamy do "Ustawienia" ale do zakładki "Home" lub "Ważne informacje" w zależności z której aktywności otworzyliśmy "Więcej". Ogólnie zawsze można używać "Więcej" zamiast back lub "Powrót". Nie wydaje się to jakimś błędem ale zawsze możesz to sprawdzić i opisać zachowanie na aktualnej wersji aplikacji w nowym issue @matsobdev.

> Plus w regulaminie urządzenie definiowanie jako Android 6.0 i więcej. Zgoda na warunki, jako zaznaczenie checkboxa??!

Obecnie wymagany jest minimum Android 5.0 i jest to też ujęte w regulaminie. A zgoda na warunki jako zaznaczenie checkboxa wydaje się powszechna/normalna. Ewentualnie to kwestia prawna jeśli coś jest nie tak a nie techniczna.
