### ISSUE TITLE
"Nie korzystamy w żaden sposób z GPS i aplikacja nie wie gdzie jesteś lub byłeś."

### ISSUE THREAD

**Issue by matsobdev** [ProteGO-Safe/android#108]
Aplikacja głosi co w tytule, a posiada uprawnienia do dokładnej lokalizacji. Do BLE wystarczy "ACCESS_COARSE_LOCATION". Bodajże jest też to niezgodne z regulaminem Google Play - aplikacja nie może posiadać uprawnień do funkcji, z których nie korzysta.

**Comment by pkleczko** [comment]
@matsobdev niestety to zmiany dla API 29 i wyżej wymuszają na nas używanie ACCESS_FINE_LOCATION. Odsyłam do [dokumentacji Google](https://developer.android.com/guide/topics/connectivity/bluetooth) związanej z wymaganymi pozwoleniami dla aplikacji korzystających z BLE.
Tak jak napisaliśmy, nie wykorzystujemy tego pozwolenia do zbierania jakiejkolwiek informacji o lokalizacji użytkownika, nasz kod jest upubliczniony i każdy może go przeanalizować czy rzeczywiście tak jest.

Daj znać proszę jeśli masz dodatkowe uwagi. Jeśli wyjaśniłem wystarczająco temat pozwolenia to będę wdzięczny za zamknięcie zgłoszenia.

**Comment by matsobdev** [comment]
Rozwiązaniem byłoby obniżenie API do 28, bo takie wystarczy obecnie dla publikacji w Google Play i pewnie nie zmieni się to do listopada tego roku i modyfikacja BlueTrace na API 28. To tylko luźna uwaga.
