### ISSUE TITLE
Zmiana strategii powiadomień

### ISSUE THREAD

**Issue by matsobdev** [ProteGO-Safe/android#109]
Częste powiadomienie, które już sygnalizują użytkownicy w komentarzach (Google Play). Obecnie wszystkie powiadomienie, w tym te najważniejsze zawarte są w jednym kanale (dodatkowo opisanym po angielsku; w ogóle nie było polskiej nazwy dla polskiej aplikacji - pytanie retoryczne). Można utworzyć oddzielne kanały (kategorie dostępne w systemowych ustawieniach aplikacji) powiadomień skojarzone z "dzióbkami" w ustawieniach aplikacji. Te mniej ważne domyślnie o niskim priorytecie tak, aby nie wyłączać wszystkich celem świętego spokoju, włącznie z powiadomieniem o kontakcie z zarażonym!
 
![Screenshot_20200429-104417_Settings](https://user-images.githubusercontent.com/63716661/80585300-62833880-8a13-11ea-8639-44cf56dcdc74.jpg)

**Comment by pkleczko** [comment]
@matsobdev słuszna uwaga, przygotujemy odpowiednie kanały i wdrożymy. i z pewnością dodamy polskie nazwy..

**Comment by Tarvald** [comment]
@matsobdev 
Zgłoszenie jest przyjęte. Trwają prace nad rozwiązaniem problemu.
Wewnętrzny numer zgłoszenia to: PSAFE-602
