### ISSUE TITLE
Używanie bluetooth mimo wyłączenia zgody używa go w celu skanowania

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#111]
W aplikacji mimo wyłączenia zgody na używanie bluetooth używa go w celu skanowania. Skanowanie włącza się samoistnie. Powiadomienie zawsze znika wraz z wyłączeniem zgody na używanie bluetooth, jak widać na gifie mimo wyłączonej zgody na używanie bluetooth w ustawieniach aplikacji powiadomienie nadal jest co jest równoznaczne ze skanowaniem. 
![Screenrecorder-2020-04-30-20-10](https://user-images.githubusercontent.com/26818304/80750426-5a68ed00-8b28-11ea-863f-cb95055bfdfe.gif)
Dodam że wcześniej (na innej wersji aplikacji chociaż może to nie mieć znaczenia) również zauważyłem że aplikacja skanuje w tle bez takiego ustawienia w aplikacji. Zrobiłem dodatkowo kilka ustawień w MIUI - brak zgody na autostart, najbardziej restrykcyjne ograniczenia zużycia baterii, wyrzuciłem aplikację z pamięci, po pewnym czasie widziałem komunikat w powiadomieniach że aplikacja skanuje. Po wyczyszczeniu danych i wyłączeniu i włączeniu bluetooth w telefonie problem nie powrócił więc nie wiem co mogło pomóc finalnie. A piszę o tym aby ktoś też zwrócił uwagę na takie zachowanie.
Wersja 3.0.2, Android 10, Xiaomi Mi 9.

**Comment by pkleczko** [comment]
@olekstomek dzięki za informację, zbadamy temat i spróbujemy odtworzyć ten błąd

**Comment by Tarvald** [comment]
@olekstomek 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-828

**Comment by olekstomek** [comment]
Nie wiem czy komuś udało się odtworzyć ten przypadek ale u mnie opisany problem występuje cały czas i jest powtarzalny. Nie znalazłem póki co zależności.

**Comment by pkleczko** [comment]
w 4.X nie ma tej funkcjonalności
