### ISSUE TITLE
Usunięcie zbędnych komponentów opentrace

### ISSUE THREAD

**Issue by PawelDedio** [ProteGO-Safe/android#113]
**Is your feature request related to a problem? Please describe.**
Aplikacja zawiera cały kod opentrace łącznie z widokami, aktywnościami itp. Po wstępnym review zauważyłem, że ProteGo wykorzystuje z opentrace jedynie część odpowiedzialną za śledzenie kontaktów, bez części widokowej. Wobez czego finalna aplikacja zawiera niepotrzebne pliki, zwiększające jej rozmiar.

**Describe the solution you'd like**
Aplikacja powinna zawierać tylko wykorzystywane komponenty z opentrace

**Comment by jasisz** [comment]
Pozostałości po SafetyNet też nie są po 3.0.3 do niczego potrzebne.

**Comment by Tarvald** [comment]
Zgłoszenie jest przyjęte. Trwają prace nad rozwiązaniem problemu.
Wewnętrzny numer zgłoszenia to:  PSAFE-790 (Android) oraz PSAFE-791 (iOS)

**Comment by pkleczko** [comment]
Mamy już w review i testach wersję która usuwa część niepotrzebnego kodu. Pracujemy również nad wersją integrującą rozwiązanie Exposure Notification od Google i tam cały kod z OpenTrace będzie usunięty, również poprawki o których wspominałem usuwające pozostałości po SafetyNet.

**Comment by Tarvald** [comment]
@PawelDedio
Najnowsza wersja dostępna w sklepie play nie posiada już pozostałości po opentrace.
Jakbyś miał jeszcze jakieś pytania to otwórz nowy wątek adekwatny do wersji 4+.

Dzięki!
