### ISSUE TITLE
Komplet danych do zbudowania aplikacji (brakujące stałe konfiguracyjne)

### ISSUE THREAD

**Issue by generatorkartwyborczych** [ProteGO-Safe/android#116]
**Describe the bug**
W obecnym stanie z publicznie dostępnych źródeł nie da się zbudować aplikacji w wersji 3.0.3

**To Reproduce**
1. Skompiluj aplikację ze źródeł wersji 3.0.3
2. Build nie powiedzie się z powodu braku definicji stałych w pliku `\opentrace\build.gradle`, na przykład `STORE_URL`, `SCAN_DURATION` czy `V2_CHARACTERISTIC_ID`

**Expected behavior**
Aplikacja się buduje.

**Comment by Tarvald** [comment]
@generatorkartwyborczych 
Zgłoszenie jest przyjęte. Trwają prace nad rozwiązaniem problemu.
Wewnętrzny numer zgłoszenia to: PSAFE-830

ps. fajny nick jak na dzien 9 maja 2020 :)

**Comment by pkleczko** [comment]
@generatorkartwyborczych celowo brakuje w projekcie zmiennych, bo projekt samodzielnie należy budować na własnym środowisku cloudowym i ze swoimi parametrami używanymi do budowania czy plikami konfiguracyjnymi do Firebase (google-services.json). Z kilku powodów dołączenie tego do kodu źródłowego nie może nastąpić:
- aplikacja jest podpisywana odpowiednim certyfikatem, który z przyczyn bezpieczeństwa nie może zostać udostępniony publicznie. Bez tego certyfikatu aplikacja, która próbowała by się łączyć do aktualnego środowiska zwyczajnie nie miała by do niego dostępu i nie działałaby prawidłowo.
- gdyby każdy mógł korzystać z instancji Firebase przewidzianej dla projektu mielibyśmy dużo ruchu z różnych, niekontrolowanych żródeł
- aplikacja w różnych konfiguracjach (środowiska developerskie, stagingowe, produkcyjne) korzysta z różnych środowisk Firebase, to też zmienne te są inne w takich przypadkach

W Readme opisaliśmy znaczenie poszczególnych zmiennych, odsyłam też do dokumentacji OpenTrace w której szczegółowo opisana jest implementacja całego systemu opartego o to rozwiązanie i wytłumaczone znaczenie zmiennych zwizanych z OpenTrace.

**Comment by tomekziel** [comment]
To może ja przeformułuję problem: jako publiczność chcielibyśmy mieć reprodukowalne buildy. Może to być nowy wariant builda, np. "repro", ze wszystkimi stałymi wypełnionymi, jak dla "prod".

Certyfikat oczywiście zostawcie w tajemnicy; aplikacja nie zadziała poprawnie podpisana czym innym - to nie jest problemem. Grunt, żeby dostać binarki, które będzie można porównywać z APK ze sklepu.

**Comment by Tarvald** [comment]
@tomekziel 
Przekazałem przeformułowany problem. 
Readme.md w /backend będzie napewno modyfikowane na dniach.

**Comment by Tarvald** [comment]
@tomekziel 
Zaktualizowano https://github.com/ProteGO-Safe/specs/blob/master/README.md
Jest tam wyjaśnione że wersja 4.0 będzie się opierać na G+A.
Taka aplikacja będzie potrzebowała dużo mniej  konfiguracji, aby ją zbudować.

Czy w takim razie będziesz potrzebować pomocy aby porównać binarki, czy sobie wtedy sam poradzisz?
Możemy udostępnić jakieś materiały, do pomocy.

**Comment by tomekziel** [comment]
> Czy w takim razie będziesz potrzebować pomocy

Mam to odgadnąć teraz?

**Comment by Tarvald** [comment]
> Mam to odgadnąć teraz?

Miałem na myśli to, że APK bedzie się budować podobnie do trudności budowania hello world'a :)

**Comment by pkleczko** [comment]
w 4.X są podane gradle.properties
