### ISSUE TITLE
Automatyczne połączenie aplikacji z Internetem gdy sieć jest dostępna

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#117]
Aplikacja powinna wykrywać automatycznie dostęp do sieci i odświeżać Aktywność bez potrzeby manualnego odświeżenia. 
![Screenshot_2020-05-09-17-49-58-868_pl gov mc protegosafe](https://user-images.githubusercontent.com/26818304/81480456-4315b800-922a-11ea-854a-ce51d40833e7.jpg)

**Comment by Tarvald** [comment]
@olekstomek
Zgłoszenie jest przyjęte. 
Wewnętrzny numer zgłoszenia to: PSAFE-832

**Comment by Tarvald** [comment]
@olekstomek 
Na tą chwile, nad tym ulepszeniem nie będą prowadzone prace, ze względu na intensywność developmentu na potrzeby 4.0 czyli rozwiązania G+A.

Ale, jeżeli chciałbyś mógłbyś zrobić PR z poprawką.
Nie wykluczone, że po wydaniu 4.0 będzie czas na ulepszanie aplikacji.

Tak czy inaczej, zgłoszenie zostaje i nigdzie nie ucieknie ;)

**Comment by pkleczko** [comment]
Dążymy do tego żeby PWA było offline, wtedy problem nie będzie występował.

**Comment by Tarvald** [comment]
Ja jednak otworze do czasu zagoszczenia offline PWA w sklepie play ;)

**Comment by Tarvald** [comment]
@olekstomek 
4.2.0 dostępne na sklepie.
Tam ten błąd nie występuje.
Problem rozwiązany :)
