### ISSUE TITLE
Dodanie utraty węchu do testu oceny ryzyka

### ISSUE THREAD

**Issue by mirekphd** [ProteGO-Safe/android#118]
**Additional context**
Wg danych Covid Symptoms Study App utrata węchu to objaw Covid-19 występujacy najczęściej (aż u 60% osób z pozytywnym testem, w tym u 16% jako wyłączny objaw), zasługuje więc moim zdaniem na pierwszą stronę triage w ProteGO-Safe, obok gorączki i kaszlu. Link:
https://podcasts.google.com/?feed=aHR0cHM6Ly9pb25vLmZtL3Jzcy9jaGFuLzIzMTk&ep=14&episode=aHR0cDovL2lvbm8uZm0vZS84NjUwMzk

**Comment by mirekphd** [comment]
Zostało to dodane, ale nie na stronie pierwszej (tam gdzie gorączka, kaszel, duszność) tylko na następnej, na końcu długiej listy 7 niezbyt specyficznych objawów. To moim zdaniem wymaga poważniejszego traktowania, gdyż mówimy tutaj o objawie który powinien być nie po bólu gardła ale przed gorączką (zaraz po pozytywnym wyniku testu laboratoryjnego).

**Comment by mirekphd** [comment]
Wyniki opublikował Lancet, i streszczenie jasno wskazuje że to najsilniejszy (dzięki nie tylko częstości - u ok. 2/3 chorych, ale i specyficzności), wyłapujący dodatkowe 16% chorych, głównie młodych pracujących (gdy pozostałe objawy są u 30%), i najdłużej (5 dni) się utrzymujący objaw. Link: https://doi.org/10.1016/S0140-6736(20)31281-2

**Comment by MateuszRomanow** [comment]
Przekazaliśmy ten temat do GIS - oni układają drzewo decyzyjne do algorytmu Triage. Dzięki za ten wątek. Jeżeli na poziomie medycznych supervisorów (GIS i MZ) zapadnie taka decyzja zaktualizujemy algorytm w sposób przez nich zaprezentowany.

**Comment by kamilgthecoders** [comment]
W wersji 4.2.4 zostało to zrealizowane. Dziękujemy za zgłoszenie. Proszę autora o zamknięcie tematu.

**Comment by mirekphd** [comment]
W porządku, rozumiem że pozycja tego objawu już w polskiej aplikacji nie wzrośnie, więc pozostaje się zadowolić tym co mamy. Zamykamy.
