### ISSUE TITLE
Internet connection detection error

### ISSUE THREAD

**Issue by igoro-pl** [ProteGO-Safe/android#124]
**Describe the bug**
On device configured with AdGuard DNS servers app reports lack of internet connection on start.

**To Reproduce**
1. Configure device with dns 176.103.130.130, 176.103.130.131, 2a00:5a60::ad1:0ff and 2a00:5a60::ad2:0ff (AdGuard "Default" set of servers)
2. Click on app icon in launcher
3. See error

**Expected behavior**
Normal application start (safesafe.app page work with this dns, app also work normally with dns changed after start)

**Screenshots**
![Screenshot_2020-06-07-21-19-16](https://user-images.githubusercontent.com/55637761/84185734-ba3fa580-aa8f-11ea-9815-0c5f3c2fd11d.png)

**Smartphone (please complete the following information):**
 - Device: LG V30 (H930DS)
 - OS: Android 8.0.0 (V22j-GLOBAL-COM)

**Additional context**
Dns changed using "VPN" redirecting dns queries

**Comment by pkleczko** [comment]
W wersji 4.2 moduł PWA nie będzie pobierany już z serwera tylko dodany do kodu aplikacji. Wtedy problem nie powinien występować.

**Comment by igoro-pl** [comment]
Dzięki, trochę się zdziwiłem, że obecna wersja (pozbawiona części rozwiązań
obecnych wcześniej) potrzebuje internetu do działania.

-- 
Igor Osipiuk

Pt., 12 cze 2020, 10:05 użytkownik Pawel Kleczkowski <
notifications@github.com> napisał:

**Comment by Tarvald** [comment]
@igoro-pl 
Zostały podane konkretne daty co do wydania wersji 4.2
https://github.com/ProteGO-Safe/specs/issues/201

**Comment by Tarvald** [comment]
Fix w 4.2.0

**Comment by Tarvald** [comment]
4.2.0 dostępne w google play. 
Problem rozwiązany :)

**Comment by igoro-pl** [comment]
potwierdzam, dzięki
