### ISSUE TITLE
Znaki specjalne w polu wyszukiwania crashują aplikację

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#128]
**Describe the bug**
Białe tło po wpisaniu w pole wyszukiwania przykładowych znaków:
```
???
***
(*)
```
itd, wygląda na problem z regexami.

**To Reproduce**
1. W aplikacji przejdź do zakładki Pytania i odpowiedzi
2. W pole wyszukiwania wprowadź przykładowo znaki: +++
3. Aplikacja przestaje działać - białe tło

**Expected behavior**
Aplikacja powinna być odporna na takie ciągi znaków specjalnych

**Screenshots**
!aplikacja od pewnej wersji blokuje robienie screenshotów

**Desktop (please complete the following information):**
 Nie dotyczy

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Mi 9]
 - OS: [Android 10]
 - Browser [Chrome]
 - Version [83]

**Additional context**
Sprawdzone na najnowszej wersji.

**Comment by Tarvald** [comment]
@olekstomek 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-1304

Czekam na info czy pójdzie w 4.2.1 czy w kolejnym release i dam znać.

**Comment by TomaszMolenda** [comment]
Zadanie zostało zrealizowane (MR https://github.com/SafeSafe-app/pwa/pull/191).
Wydane zostanie w najbliższej wersji 4.3.0

**Comment by olekstomek** [comment]
Do zamknięcia, problem nie występuje. 👍
