### ISSUE TITLE
Aplikacja pokazuje pomarańczowy status Użytkownika

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/android#13]
Aplikacja odpytuje serwer i pokazuje Użytkownikowi pomarańczowy status

**Comment by jakublipinski** [comment]
Można zamknąć?

**Comment by mikolak** [comment]
Brakuje odpytania serwera, żółty/pomarańczowy jest zabity gwoździami.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
