### ISSUE TITLE
Tell me how many contacts were checked

### ISSUE THREAD

**Issue by dagguh** [ProteGO-Safe/android#130]
**Is your feature request related to a problem? Please describe.**
I don't know how valuable the exposure tracking is. I don't know how many people around me use it. When I get the notification that I was not exposed, I don't know if I can feel safe.

**Describe the solution you'd like**
 If the app told me "Out of 40 contacts, you were exposed 0 times", I'd feel much better. Especially if I remember 60 contacts (very roughly) in the past 14 days.

**Describe alternatives you've considered**
I keep promoting the app to my friends and family. But I don't know about strangers (sometimes it's hard to avoid medium-range contact). Also, if I could show them this feature, it could be more convincing to them.

PS. the issue template was in English, so I wrote it in English. Let me know if I should post it in Polish.

**Comment by pkleczko** [comment]
Tak, używamy tutaj polskiego języka, więc jeśli takim się posługujesz będzie mi wygodniej odpisać po polsku.

Co do zasady Exposure Notification dostarczane przez Google/Apple nie pozwala ze względów na prywatność i bezpieczeństwo na dostęp do informacji o tym ile kontaktów zostało zarejestrowanych, nie jest więc możliwe pokazanie takiej informacji w aplikacji. Mimo pozytywnych aspektów takiej funkcjonalności, o których wspominasz niosło by to za sobą sporo ryzyk i potencjalnych naruszeń prywatności. Wyobraź sobie np. sytuację że żyjesz w małej społeczności, dzięki temu mógłbyś dowiedzieć się kto używa aplikacji, również potencjalnie kto dokładnie jest pozytywnie zdiagnozowany. Więcej dyskusji na ten temat znajdziesz w projekcie 'specs'.

Jeśli rozwiązałem Twoje wątpliwości to proszę o zamknięcie issue, ewentualnie przerzucenie się na 'specs', nie jest to błąd aplikacji.

**Comment by dagguh** [comment]
Rozumiem wytłumaczenie, dzięki

**Comment by maciejs** [comment]
A o czym mówią te liczby w ustawieniach Google Play, czy ktoś może to wyjaśnić? 

ustawienia telefonu -> Google -> Powiadomienia o narażeniu na kontakt z COVID-19 -> Kontrola ryzyka narażenia na kontakt -> nacisnąć na godzinę

![sketch-1596392689496](https://user-images.githubusercontent.com/3775014/89129592-c0d22280-d4fe-11ea-860d-55261aec7bd2.png)
