### ISSUE TITLE
Niepoprawne wyświetlanie treści w aplikacji w trybie ciemnym Xiaomi

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#131]
**Describe the bug**
Po włączeniu trybu ciemnego dla aplikacji w Xiaomi, nie wszystkie informacje tekstowe są widoczne - są puste białe pola a pozostają jedynie rysunki/grafiki. Np. na pierwszej stronie po otwarciu aplikacji nie jest widoczna informacja tekstowa "..., przeanalizowaliśmy Twoje odpowiedzi..."

**To Reproduce**
Dotyczy Xiaomi ale warto sprawdzić tryby ciemne i zachowanie na smartfonach innych firm i wersjach Androida.

1. Wejdź w ustawienia -> Wyświetlacz -> Tryb ciemny -> włącz
2. Otwórz aplikację ProteGO-Safe i sprawdź widoczność tekstów w aplikacji
3. Wróć do miejsca z punktu 1. Wybierz "Poszczególne aplikacje" i odznacz  tryb ciemny dla ProteGO-Safe. Teraz treść aplikacji wyświetlana jest prawidłowo. 

**Expected behavior**
Treść powinna być widoczna prawidłowo w każdym trybie.

**Screenshots**
brak możliwości zrobienia zrzutu ekranu

**Desktop (please complete the following information):**
 nie dotyczy

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 10
 - Browser Chrome Mobile
 - Version 83

**Additional context**
Przy konfiguracji telefonu przy pierwszym uruchomieniu i wybraniu motywu ciemnego jest on domyślnie ustawiamy dla wszystkich aplikacji (tak widzę w ustawieniach). Czyli problem może być powszechny.

**Comment by Tarvald** [comment]
@olekstomek 
Sprawdziliśmy na kilku telefonach, ale akurat nie posiadamy Mi 9 z Androidem 10.

Jednak w moim przypadku:
- na note 8t android 9 + ciemny motyw wszystko ok
- lg g7 android 10 + ciemny motyw wszystko ok

Czy ty po przełączeniu telefonu na tryb ciemny masz inne kolory w aplikacji? U mnie pozostają takie same.
Może to głupie... ale mógłbyś zrobić zdjęcie swojego telefonu?

Brak możliwości robienia screenshotów równierz wynika z polityki prywatności :(

Dzięki

**Comment by olekstomek** [comment]
@Tarvald nie ma problemu, dodaję zdjęcia (wcześniej nie dodałem bo myślałem że się uda go odtworzyć Wam). :)

Moja diagnoza: należy rozróżnić dwie opcje: [Tryb ciemny i Odwrócenie kolorów](https://support.google.com/accessibility/android/answer/6151800?hl=pl). 
W tym linku jest odpowiedź wg mnie - dlaczego PLA w aplikacji ProteGO-Safe nie jest zmieniane i dostosowywane do trybu ciemnego Androida:

> Tryb ciemny dotyczy interfejsu systemu Android i obsługiwanych aplikacji. Kolory nie zmieniają się w multimediach (np. filmach).

Ale problem istnieje.

**1. Bez włączonego trybu ciemnego jest oczywiście OK:**
![IMG_20200703_113919](https://user-images.githubusercontent.com/26818304/86459086-8ff7a580-bd26-11ea-97af-6a2dd106afca.jpg)
![IMG_20200703_113926](https://user-images.githubusercontent.com/26818304/86459093-9259ff80-bd26-11ea-9694-a409fb0447c2.jpg)

**2. Włączam Tryb ciemny:**
![IMG_20200703_114047](https://user-images.githubusercontent.com/26818304/86459273-d51bd780-bd26-11ea-8626-2b3515857ec8.jpg)
![IMG_20200703_114202](https://user-images.githubusercontent.com/26818304/86459222-c7fee880-bd26-11ea-9e50-b22f1309b57f.jpg)
![IMG_20200703_114213](https://user-images.githubusercontent.com/26818304/86459231-ca614280-bd26-11ea-9e27-ada325f04b1a.jpg)
![IMG_20200703_114222](https://user-images.githubusercontent.com/26818304/86459234-caf9d900-bd26-11ea-9893-ee7980d60ddd.jpg)
![IMG_20200703_114236](https://user-images.githubusercontent.com/26818304/86459237-cc2b0600-bd26-11ea-8c00-2d01c1b49153.jpg)
![IMG_20200703_114245](https://user-images.githubusercontent.com/26818304/86459241-cd5c3300-bd26-11ea-8260-629267049b3f.jpg)
![IMG_20200703_114303](https://user-images.githubusercontent.com/26818304/86459245-ce8d6000-bd26-11ea-8e06-abf81223ca7d.jpg)
![IMG_20200703_114325](https://user-images.githubusercontent.com/26818304/86459248-cf25f680-bd26-11ea-82bd-5250b520c9cc.jpg)
![IMG_20200703_114342](https://user-images.githubusercontent.com/26818304/86459253-d0572380-bd26-11ea-939c-4dc89337212a.jpg)
![IMG_20200703_114402](https://user-images.githubusercontent.com/26818304/86459260-d1885080-bd26-11ea-80a9-06c46d5b3187.jpg)
![IMG_20200703_114416](https://user-images.githubusercontent.com/26818304/86459264-d220e700-bd26-11ea-8a00-003b7783e29b.jpg)
![IMG_20200703_114424](https://user-images.githubusercontent.com/26818304/86459268-d3521400-bd26-11ea-8680-8bd1f0c3e024.jpg)
![IMG_20200703_114432](https://user-images.githubusercontent.com/26818304/86459271-d3eaaa80-bd26-11ea-9b75-a77aa12b44e7.jpg)
![IMG_20200703_114109](https://user-images.githubusercontent.com/26818304/86459280-d64d0480-bd26-11ea-8bbe-54622c6281c0.jpg)
![IMG_20200703_114117](https://user-images.githubusercontent.com/26818304/86459283-d6e59b00-bd26-11ea-9f26-27b28cb6216e.jpg)
![IMG_20200703_114140](https://user-images.githubusercontent.com/26818304/86459288-d8af5e80-bd26-11ea-88ba-ee8a831d7569.jpg)

**3. W Trybie ciemnym dodatkowo włączam Odwrócenie kolorów.**
![IMG_20200703_120103](https://user-images.githubusercontent.com/26818304/86459716-8589db80-bd27-11ea-97b6-c64b089d3148.jpg)
![IMG_20200703_120130](https://user-images.githubusercontent.com/26818304/86459711-83278180-bd27-11ea-9ec1-a128bc150c46.jpg)
![IMG_20200703_120117](https://user-images.githubusercontent.com/26818304/86459719-86227200-bd27-11ea-9ad6-a11300c6a07b.jpg)

**4. Wyłączam Tryb ciemny i zostawiam Odwrócenie kolorów.**
![IMG_20200703_120439](https://user-images.githubusercontent.com/26818304/86459826-a81bf480-bd27-11ea-864b-a217a0b89785.jpg)
![IMG_20200703_120447](https://user-images.githubusercontent.com/26818304/86459831-aa7e4e80-bd27-11ea-93a5-788cca8fa83e.jpg)

Czyli podsumowując - prawidłowo działa tylko dla trybu jasnego (nieciemnego) bez odwracania kolorów (odwrócenie kolorów to fatalny - nieczytelny - widok Androida i aplikacji, poza tym sama natywna aplikacja ProteGO-Sage traci kolory layoutu). 
Aplikacja powinna zacząć obsługiwać tryb ciemny.

**Comment by Tarvald** [comment]
@olekstomek 
Wow dzięki! To naprawde pomocne.

Mamy już telefon z Xiaomi Mi 9 z Androidem 10 ale... problem nie występuje hehe.

![image](https://user-images.githubusercontent.com/7673542/86465637-5d53aa00-bd32-11ea-8e30-05671d45aa33.png)
![image](https://user-images.githubusercontent.com/7673542/86465664-65abe500-bd32-11ea-9ddd-b0dbbfd6c276.png)
(screeny z wersji developerskiej)

Czy mogłbyś podać pełną nazwe modelu z ustawień urządzenia?
Nasze to: M1902F1G

ps. używasz może jakiś nakładek systemowych?

**Comment by olekstomek** [comment]
@Tarvald u mnie Android to 10QKQ1.190825.002 z MIUI Global 12.0.1 (Stabilna) 12.0.1.0(QFAEUXM). Model dokładnie taki jak Wasz M1902F1G.
Nie używam żadnych dodatkowych nakładek (jedynie oryginalnie MIUI).
ALE, mam wrażenie że tryb ciemny nie został włączony dla aplikacji ProteGO-Safe (bo na zrzucie ekranu dolne menu jest jasne a u mnie jak widać jest ciemne). :) W trybie ciemnym trochę niżej jest sekcja "Zaawansowane" i tutaj jest opcja "Poszczególne aplikacje" gdzie można włączyć tryb ciemny dla danych aplikacji (ten tryb ciemny włączył mi się automatycznie dla wszystkich zainstalowanych aplikacji).

**Comment by Tarvald** [comment]
@olekstomek 
Wygląda na to że wszystko jasne. Poniżej wklejam odpowiedź od QA:

`Tryb ciemny został u nas włączony poprawnie na urządzeniu. Jednak wygląda na to, że problem występuje po stronie nakładki MIUI w wersji 12.
Przy identycznym buildzie Androida i identycznym modelu jedyną różnicą jest to, że na naszym urządzeniu jest MIUI w wersji 11.0.8.
Nasze urządzenie jeszcze nie otrzymało aktualizacji do wersji 12.0.X
Jest to znany problem w MIUI, który występuje w wersji 12 od czasu pierwszych wydań w kwietniu.
Postaramy się przeanalizować czy jesteśmy w stanie cokolwiek na to poradzić z naszej strony :)`

Problem został zgłoszony jako PSAFE-1328 i jak tylko coś się w tej sprawie ruszy to damy znać :)

@olekstomek 
Dzięki wielki, naprawde nam pomogłeś w rozgryzieniu co się dzieje.

**Comment by olekstomek** [comment]
@Tarvald, to super, cieszę się. ;)
Jeśli to wynika z różnic MIUI to myślę że wiele aplikacji będzie miało/ma podobny problem (przykładowo jedna z aplikacji bankowych - przy logowaniu pinem pola są całe białe po wpisaniu cyfr i ma się wrażenie że nie są wpisane wartości w te pola, i to jest logiczne, bo czarne kropki są zamieniane na białe kropki a tło dalej zostaje białe i efekt osiągnięty), więc wydaje się że to oni (Xiaomi) się fixną a przynajmniej powinni. :)

**Comment by patrys** [comment]
Problem występuje u mnie tylko w tej aplikacji. Wygląda na to, że aplikacja korzysta z systemowego koloru fontów, natomiast wymusza swój kolor tła.

**Comment by olekstomek** [comment]
Poczytałem komentarze w Google Play i szczególnie się zaskoczyłem jak ustawiłem na filtr "Ten model urządzenia" - czyli urządzenia na którym wyżej dokumentowałem problem i ile jest komentarzy że nie widać treści w aplikacji. A to dotyczy nie tylko tego modelu ale MIUI więc wszystkich Xiaomi. Użytkownicy w komentarzach są odsyłani przez "Ministerstwo Cyfryzacji" do tego wątku ale uważam że nie jest to dla nich rozwiązanie którego oczekują - czytanie tego wątku i dostosowywanie ustawień Androida po to aby aplikacja działała prawidłowo, to aplikacja ma się dostosować i działać OOTB.  Wydaje się że ten hotfix https://github.com/ProteGO-Safe/android/pull/144 oszczędziłby negatywnych komentarzy i negatywnych ocen w sklepie Play a jednocześnie dalej możnaby pracować nad innym rozwiązaniem z dark mode, lepszym/poprawniejszym? PR sprzed dwóch miesięcy został zamknięty, niezmergowany i jednocześnie nie został ten problem rozwiązany. A problem jest poważny - uniemożliwia korzystanie z aplikacji bez ingerencji w ustawienia systemowe MIUI i jest to blockerem dla użytkowników końcowych. 
Na czym obecnie zatrzymały się prace?

**Comment by olekstomek** [comment]
@MateuszRomanow podbijam.

> Użytkownicy w komentarzach są odsyłani przez "Ministerstwo Cyfryzacji" do tego wątku

![image](https://user-images.githubusercontent.com/26818304/99774760-853f8080-2b0e-11eb-93f7-e3442532c924.png)

(tylko komentarze gdzie została dodana odpowiedź z linkiem do tego wątku i tylko komentarze użytkowników którym chciało się napisać że mają problem).

**Comment by JulianVolodia** [comment]
Hej Kamil @qLb może jednak zmergujesz "mitygację"? :)

https://github.com/ProteGO-Safe/android/pull/144#issuecomment-762725677

Od "sprzed świąt" wiszą tickety które miały zostać naprawione. Trzeba w czymś pomóc? : )

**Comment by JulianVolodia** [comment]
> Czyli podsumowując - prawidłowo działa tylko dla trybu jasnego (nieciemnego) bez odwracania kolorów (odwrócenie kolorów to fatalny - nieczytelny - widok Androida i aplikacji, poza tym sama natywna aplikacja ProteGO-Sage traci kolory layoutu).
> Aplikacja powinna zacząć obsługiwać tryb ciemny.

@qLb ^^^ nie zadziała przez to też dla osób wymagających ustawienia "zwiększonego kontrastu".

**Comment by SknerusMcK** [comment]
Kiedy to w końcu zostanie naprawione? Jest gotowy fix, ale nie bo programiści mają takie widzimisię... https://github.com/ProteGO-Safe/android/pull/144
Chociaż teraz to w sumie jest już za późno, bo wszyscy użytkownicy Xiaomi wrzucili apkę do szufladki "nie instalować, gówno" i tyle.

**Comment by olekstomek** [comment]
> @MateuszRomanow podbijam.
> 
> > Użytkownicy w komentarzach są odsyłani przez "Ministerstwo Cyfryzacji" do tego wątku
> 
> ![image](https://user-images.githubusercontent.com/26818304/99774760-853f8080-2b0e-11eb-93f7-e3442532c924.png)
> 
> (tylko komentarze gdzie została dodana odpowiedź z linkiem do tego wątku i tylko komentarze użytkowników którym chciało się napisać że mają problem).

bump
![image](https://user-images.githubusercontent.com/26818304/109035901-5f0b1d00-76c9-11eb-9a81-dd6c1245e0bc.png)
🤷‍♂️

**Comment by SknerusMcK** [comment]
Można sobie podbijać, ale to i tak nic nie da bo jak widać twórcy są po prostu niepoważni...

**Comment by pkleczko** [comment]
Temat rzeczywiście nam lekko mówiąc utknął, oprócz zablokowania dark mode całkowicie liczyliśmy na poprawkę/zmianę działania od Xiaomi oraz rozważaliśmy po prostu zrobienie pełnoprawnego Dark Mode, ale z przyczyn już niezależnych od nas ta opcja nie będzie wprowadzona. Stąd, w wersji 4.10.0, która wyjdzie w marcu znajdzie się [workaround ](https://github.com/ProteGO-Safe/android/pull/144) zaproponowany przez @Faierbel żeby rozwiązać problem.

**Comment by olekstomek** [comment]
Problem już nie występuje. Można również znaleźć potwierdzenia w komentarzach na Google Play.
