### ISSUE TITLE
Różne number version aplikacji w Google Play i w samej aplikacji

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#132]
**Describe the bug**
W Google Play widzę wersję aplikacji: wersja 4.2.**1**
W smartfonie widzę wersję aplikacji: 4.2.**0** (update aplikacji wczoraj)

**To Reproduce**
Sprawdzić wyświetlaną wersję aplikacji w telefonie można po klliknięciu w zakładkę "Więcej".

**Expected behavior**
Aktualna wersja aplikacji powinna mieć ten sam numer wersji co aplikacja w Google Play.

**Screenshots**
![version_apk](https://user-images.githubusercontent.com/26818304/87033256-2a079400-c1e6-11ea-84a5-fcb519987697.png)

**Desktop (please complete the following information):**
/-

**Smartphone (please complete the following information):**
Device: Xiaomi Mi 9
OS: Android 10
Browser Chrome Mobile
Version 83

**Additional context**
`name":"ProteGoSafe","version":"4.2.0","` w [app/src/main/assets/pwa/static/js/main.ab0fa471.chunk.js](https://github.com/ProteGO-Safe/android/blob/master/app/src/main/assets/pwa/static/js/main.ab0fa471.chunk.js)
` <Version>wersja: {version}</Version>` w [app/src/main/assets/pwa/static/js/main.ab0fa471.chunk.js.map](https://github.com/ProteGO-Safe/android/blob/master/app/src/main/assets/pwa/static/js/main.ab0fa471.chunk.js.map)
to tylko miejsca występowania wersji bo commity są do tyłu względem wersji aplikacji w Google Play.
Być może zamiast hardkodować wersję w _main.ab0fa471.chunk.js_ powinna być ona przypisywana z _versionName_ z [build.gradle](https://github.com/ProteGO-Safe/android/blob/master/app/build.gradle).

**Comment by pkleczko** [comment]
Dzięki za zgłoszenie. Problem wynika z tego, że mamy tutaj moduł PWA (webowy UI), który ma oddzielne wersjonowanie i pokazuje wersję tej części aplikacji. Ale zastanowimy się nad dodaniem również informacji o wersji aplikacji mobilnej, może to być dobrym pomysłem aby pokazać obie wersje.

**Comment by pkleczko** [comment]
dodaliśmy pokazywanie wersji aplikacji natywnej w części PWA i teraz powinna się zawsze zgadzać z wersją aplikacji. prośba o retest i ewentualne zamknięcie issue.

**Comment by olekstomek** [comment]
Po ostatniej aktualizacji wersja aplikacji wyświetla prawidłową wartość.
