### ISSUE TITLE
Onboarding na Androidzie przeskakuje ekran aktywacji protokołu EN

### ISSUE THREAD

**Issue by tomekziel** [ProteGO-Safe/android#134]
**Describe the bug**
Onboarding na Androidzie przeskakuje ekran aktywacji protokołu EN, który powinien być drugim ekranem w kolejności.

**To Reproduce**
1. Świeża instalacja, włączyć aplikację
2. Na ekranie tytułowym kliknąć "Rozpocznij"
3. Ekran "Wszystko w Twoich rękach" (B) nie pojawia się. Zamiast tego widać ekran "Powiadomienia o narażeniu" (A)

**Expected behavior**
Pokazanie w drugim kroku "Wszystko w Twoich rękach", w przeciwnym razie druga szansa pojawi się dopiero na 16. ekranie onboardingu

**Screenshots**
<img src="https://user-images.githubusercontent.com/1764747/87644250-304cc180-c74c-11ea-96a4-5919d8702c86.png" width="400">

**Smartphone (please complete the following information):**

Usterka potwierdzona na 13 różnych telefonach - 4 moich i 9 u osób które odpowiedziały na apel na Twitterze i  innych social mediach (https://twitter.com/InfZakladowy/status/1282811062484717568)

Jedyne urządzenie, na którym widzę ekran "B", to zrootowany Nexus 5x na stockowym sofcie 8.1 a i tam pojawia się jednokrotnie i zabicie procesu na ekranie "Rozpocznij" sprawi, że przy drugim uruchomieniu apka pokaże jako drugi ekran "A".

**Additional context**
Ta usterka może dramatycznie zwiększać liczbę ludzi, którzy zainstalują i uruchomią ProteGO Safe, ale nie zauważą opcji aktywacji Exposure Notification na 16. ekranie licząc od początku onboardingu więc nie uruchomią rozgłaszania.

**Comment by pkleczko** [comment]
Dzięki za zgłoszenie błędu. Nad rozwiązaniem problemu pracujemy, z naszych testów wyszło że pojawia się głównie po reinstalacji zaraz po odinstalowaniu, przy pierwszej instalacji na ok 60 testowanych urządzeniach ani razu nie wystąpił za pierwszym razem. Czy możesz potwierdzić że wykonane testy nie dotyczyły kolejnych instalacji apki? Co nie zmienia faktu, że powinno być to 100% niezawodne i jak wspomniałem pracujemy nad poprawką. Najprawdopodobniej mamy tutaj problem klasycznego "wyścigu", który uśpił naszą czujność i przedarł się przez przeprowadzane testy.

Uwagi słuszne, nie mniej a) wybrałeś najdłuższą ścieżkę dotarcia do dashboard (z dziennikarskiej uczciwości warto byłoby wspomnieć jaka jest najkrótsza gdy pomijasz Test Oceny Ryzyka b) na dashboard mamy bardzo wyraźny warning o braku aktywnej funkcji EN, który pozwala na jej włączenie i mityguje problem braku jego włączenia zaraz po pierwszym uruchomieniu (oczywiście możemy gdybać jaka jest jego skuteczność, nie mamy żadnych danych ile osób dotarło do tego miejsca i nie włączyło EN)

**Comment by tomekziel** [comment]
> Czy możesz potwierdzić że wykonane testy nie dotyczyły kolejnych instalacji apki?

Na pewno na Galaxy S7 Edge (Android 8.0) instalowałem ProteGO Safe po raz pierwszy i problem też tam wystąpił. Mam też wrażenie, że na jednym z urządzeń była wcześniej tylko wersja 3.x, ale nie wiem, jak informacja o tym ma przedostawać się pomiędzy instalacjami.

**Comment by pkleczko** [comment]
@tomekziel prośba o retest na wersji 4.2.3

**Comment by tomekziel** [comment]
4.2.3 - za każdym razem OK
