### ISSUE TITLE
Gdy aplikacja jest nieaktualna, przestaje działać bez informowania mnie o tym

### ISSUE THREAD

**Issue by jembezmamy** [ProteGO-Safe/android#139]
**Opis błędu**

Używam tej aplikacji od ponad miesiąca i w tym czasie już dwa razy przestała kontrolować ekspozycję na koronawirusa. Wydaje mi się, że ma to miejsce wtedy, gdy nie zainstaluję aktualizacji.

**Jak odtworzyć błąd**

Co zrobić, żeby odtworzyć błąd:
1. Zainstalować ProteGO Safe,
2. Wyłączyć automatyczne aktualizacje,
3. Poczekać aż zainstalowana aplikacja będzie nieaktualna,
4. Wejść w Ustawienia Google / Powiadomienia o narażeniu na kontakt z COVID-19,
5. Sprawdzić datę ostatniej kontroli - kontrole nie są wykonywane odkąd aplikacja jest nieaktualna.

**Spodziewane zachowanie**

Chciałbym, żeby aplikacja działała nadal pomimo braku zainstalowanych aktualizacji. Jeśli to problem, to niech przynajmniej wyświetli mi powiadomienie, że przestała działać. Obecnie ja muszę ciągle ją kontrolować, czy ona działa, i to jest uciążliwe, na dłuższą metę to mi się nie chce.

**Sprzęt**

 - Urządzenie: LG-H320
 - System: Android 5.0.1
 - Przeglądarka: Chrome
 - Wersja ProteGO Safe: 4.2.2

**Dodatkowe informacje**

Mam wyłączone automatyczne aktualizacje, bo jak je włączę, to mi zabraknie pamięci.

**Comment by pkleczko** [comment]
Akurat weszła aktualizacja do 4.2.3, więc sprawdziłem opisywany scenariusz i mimo informacji że jest nowa wersja dostępna do zainstalowania to aplikacja nadal monitoruje ryzyko.
Wydaje mi się, że ten problem nie jest związany z aktualizacją aplikacji tylko innym problemem. Spróbujemy go odtworzyć, niemniej Android 5.0.1 mimo że postanowiliśmy udostępnić dla niego aplikację, to nie jest przez nas aktywnie wspierany. Przyjrzymy się jednak czy problem da się odtworzyć na tym i nowszych wersjach systemu.

**Comment by jembezmamy** [comment]
Ok, dzięki za wyjaśnienie. Może rzeczywiście nie ma to związku z aktualizacją.

Kiedy otworzę aplikację bez instalowania aktualizacji, to mam taki ekran, że muszę najpierw ją zaktualizować. Dlatego wydawało mi się, że ona przestaje całkowicie działać i czeka, aż ją zaktualizuję.

Natomiast w logu kontroli ekspozycji mam naprawdę mało kontroli - obecnie 4 w ciągu ostatnich 14 dni (17.07, 2 x 21.07 i 31.07). Ale może właśnie to ma tak wyglądać?

Tak naprawdę to mój problem jest totalnie UX-owy, tzn. ja mam wrażenie, że ta aplikacja przestaje działać i mi o tym nie mówi. Chyba czułbym się lepiej, gdyby raz w tygodniu ona mi wyświetla powiadomienie, że wszystko jest pod kontrolą i nie muszę się niczym martwić. Albo gdyby w samej aplikacji był codzienny log kontroli - żebym miał jakieś potwierdzenie, że ona działała przez ten cały czas, kiedy jej nie uruchamiałem. W sumie raz, na samym początku używania tej aplikacji, dostałem powiadomienie, że w ciągu minionego tygodnia nie wykryto ekspozycji (jakoś tak), ale potem nigdy to się już nie powtórzyło.

**Comment by pkleczko** [comment]
ok, zastanowimy się nad tym czy w samej aplikacji czegoś dodatkowo nie pokazać. aplikacja przechowuje minimum informacji i dlatego nie ma "statystyk" sprawdzeń, są one tak jak wspomniałeś w ustawieniach Google i z racji że ilość użytkowników rośnie powoli (chociaż zauważamy wzrost pobrań po ostatnich wzrostach ilości osób zakażonych) to i póki co mamy mało paczek do sprawdzenia i jest to normalne że w ciągu 14 dni było ich zaledwie kilka.

**Comment by jembezmamy** [comment]
Świetnie, dzięki!

**Comment by pkleczko** [comment]
czy możemy zamknąć issue?

**Comment by jembezmamy** [comment]
Tak :) zamykam
