### ISSUE TITLE
No English locale

### ISSUE THREAD

**Issue by jackszm** [ProteGO-Safe/android#141]
**Is your feature request related to a problem? Please describe.**

No English locale within the app. App is unusable unless you are know polish. 

**Describe the solution you'd like**

To add English locale to the app.

**Comment by olekstomek** [comment]
It will be implement. https://github.com/ProteGO-Safe/specs/issues/220

**Comment by MateuszRomanow** [comment]
English and Ukrainian translation will be implemented in the next release. Issue to be close.
