### ISSUE TITLE
Nieprawidłowy format godziny wykonania testu

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#147]
Po wykonaniu testu jest następujący komunikat (część):
_Wynik testu z 9-09-2020 (03:35) kwalifikuje Cię do grupy_

Godzina 03:35 mimo że test wykonany o 15:35. Wykonując taki test faktycznie nad ranem o 03:35 również będzie to godzina 03:35. W polskim formacie czasu jest to nieprawidłowy czas i błędny o 12h dla godzin PM.

**Comment by thecodersio** [comment]
Dziękujemy za informację :) 

Numer wew. zadania: SCPSU-206

**Comment by pkleczko** [comment]
Problem został rozwiązany w wersji 4.4.0 aplikacji. Prośba o weryfikację i zamknięcie Issue jeśli jest ok.

**Comment by olekstomek** [comment]
Jest OK. Problem rozwiązany.
