### ISSUE TITLE
Brak możliwości zamknięcia aplikacji przez "back" po wypełnieniu ankiety

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#151]
**Describe the bug**
Brak możliwości zamknięcia aplikacji przez "back" po wypełnieniu ankiety.

**To Reproduce**
1. Wykonaj w całości ankietę "Wykonaj TEST oceny ryzyka" i zatwierdź ankietę
2. Naciśnij dwa razy i kilkakrotnie androidowy "back" aby zamknąć aplikację

**Current behavior**
Aplikacja nie jest zamykana. Efekt jest taki jakby aktywność była odświeżana/ponownie otwierana.

**Expected behavior**
Aplikacja powinna się prawidłowo zamknąć.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device model: Xiaomi Mi 9
 - OS: Android 10.0

**Additional context**
Wersja 4.4.0

**Comment by pkleczko** [comment]
Problem powinien już być naprawiony od wersji 4.5.0. Prośba o weryfikację i zamknięcie issue.

**Comment by olekstomek** [comment]
Release 4.5.0 (https://github.com/ProteGO-Safe/android/pull/155) rozwiązuje ten problem. Działa OK.
