### ISSUE TITLE
Aplikacja nie pokazuje dalszych instrukcji po kliknięciu powiadomienia

### ISSUE THREAD

**Issue by Grze-Wo** [ProteGO-Safe/android#153]
**Describe the bug**
Według publicznie dostępnych informacji aplikacja powinna pokazać jakie możne wykonać kroki po otrzymaniu powiadomienia o narażeniu na kontakt z zarazoną osobą. Tak się jednak nie dzieje. Po kliknięciu komunikatu aplikacja się otwarła a widoczny ekran był standardowym ekranem widocznym na starcie. 
Aplikacja nie zawiera żadnego rejestru powiadomień więc nie można zweryfikować kiedy taki komunikat otrzymano. Osoby nietechniczne bardzo często nie czytają komunikatów i nie usuwają ich, nie wiedzą przez to kiedy mogli się zarazić a przez to nie wiedzą do kiedy oczekiwać wystąpienia objawów. 

**To Reproduce**
1. Otrzymaj komunikat o treści wskazującej na kontakt z osobą zarażoną
2. Kliknij w niego
3. Aplikacja się otworzy na domyślnym ekranie. Zaobserwuj brak dalszych informacji. Zaobserwuj brak listy komunikatów. 

**Current behavior**
Brak oczekiwanych informacji po kliknięciu w komunikat. A także brak listy komunikatów z datami otrzymania

**Expected behavior**
Otrzymanie info o dalszych krokach po otrzymaniu komunikatu. 
Dodanie listy komunikatów w aplikacji wraz z powyższą instrukcja co dalej robić. 

**Screenshots**
W tym wypadku nieistotne

**Smartphone (please complete the following information):**
 - Device model: LG K40 model LM-X420EMW
 - OS: Android 9

**Additional context**
Telefon osoby nietechnicznej. Nie wiadomo jak długo powiadomienie było widoczne, ale nie dłużej niż ok 2 tygodnie.

**Comment by pkleczko** [comment]
@Grze-Wo czy mamy pewność że była to notyfikacja o wykrytym kontakcie z inną osobą czy może było to powiadomienie z podsumowaniem tygodniowym o przeprowadzonych analizach wykrycia kontaktu? Taka notyfikacja wyświetlana jest przez system raz na tydzień, ale w jej konsekwencji w aplikacji nic dodatkowego nie jest wyświetlane. Ma ona tylko i wyłącznie informacyjny cel o tym, że moduł analizy Exposure Notification cały czas działa i analizuje kontakt z kluczami pobranymi z CDNa. Ewentualnie przydatna byłaby informacja kiedy powiadomienie się pojawiło a kiedy zostało "kliknięte". Przykładowo jeśli dnia X pokazało się powiadomienie, które wykryło kontakt 14 dni temu to dnia X+1 ryzyko jest już nieaktualne i wtedy aplikacja nie pokaże żadnego komunikatu. Czyli jeśli powiadomienie zostało kliknięte kolejnego dnia może nie być widoczna informacja o wykrytym zagrożeniu. Zakładam małą szansę na taki przypadek, ale z racji że nie mamy żadnych statystyk i logów aby zdiagnozować problem potrzebujemy szczegółowych informacji o problemie. 

Czy problem u danej osoby się powtórzył?

**Comment by Grze-Wo** [comment]
> @Grze-Wo czy mamy pewność że była to notyfikacja o wykrytym kontakcie z inną osobą czy może było to powiadomienie z podsumowaniem tygodniowym o przeprowadzonych analizach wykrycia kontaktu? Taka notyfikacja wyświetlana jest przez system raz na tydzień, ale w jej konsekwencji w aplikacji nic dodatkowego nie jest wyświetlane. Ma ona tylko i wyłącznie informacyjny cel o tym, że moduł analizy Exposure Notification cały czas działa i analizuje kontakt z kluczami pobranymi z CDNa. Ewentualnie przydatna byłaby informacja kiedy powiadomienie się pojawiło a kiedy zostało "kliknięte". Przykładowo jeśli dnia X pokazało się powiadomienie, które wykryło kontakt 14 dni temu to dnia X+1 ryzyko jest już nieaktualne i wtedy aplikacja nie pokaże żadnego komunikatu. Czyli jeśli powiadomienie zostało kliknięte kolejnego dnia może nie być widoczna informacja o wykrytym zagrożeniu. Zakładam małą szansę na taki przypadek, ale z racji że nie mamy żadnych statystyk i logów aby zdiagnozować problem potrzebujemy szczegółowych informacji o problemie.
> 
> Czy problem u danej osoby się powtórzył?

**Comment by pkleczko** [comment]
mamy tutaj 2 sprzeczne oczekiwania. z jednej strony dużo razy społeczność chociażby tutaj na GH nawoływała do tego żeby aplikacja przetwarzała i przechowywała minimum danych a z drugiej strony wszyscy jesteśmy ciekawi statystyk z jej działania. poszliśmy drogą minimalizmu i braku historii sprawdzeń i wykryć nawet jeśli miałoby to być przechowywane tylko lokalnie. Dzięki temu nikt nie ma obaw że przy kolejnej aktualizacji wprowadzony zostałby mechanizm wysyłający te dane gdzieś na serwer. W konsekwencji nie jesteśmy w stanie skutecznie informować użytkownika czy pomóc zdebugować tego typu przypadki. Problem jest od jakiegoś czasu zauważony i dyskutujemy nad wprowadzeniem formy lokalnych statystyk z chociażby ilości sprawdzeń czy wyświetleń notyfikacji jednak żadne decyzje jeszcze nie zapadły. Takie statystyki są też dostępne z poziomu Ustawień telefonu w zakładce dla Powiadomień o ekspozycji.

**Comment by Grze-Wo** [comment]
`społeczność chociażby tutaj na GH nawoływała do tego żeby aplikacja przetwarzała i przechowywała minimum danych` słuszne wymaganie dla tej konkretnej aplikacji `a z drugiej strony wszyscy jesteśmy ciekawi statystyk z jej działania` niekoniecznie - jako bardzo nietechniczny użytkownik oczekuję aby aplikacja prowadziła mnie za rączkę a nie aby poznać każdą linijkę loga. W kontekście zgłoszenia oczekuję zarejestrowania **tylko** tej właśnie notyfikacji o kontakcie z osobą zarażoną (być może także jej treści) oraz kroków jakie powinienem podjąć dalej (jeśli notyfikacja wygasła to też można coś napisać). I tyle. Żadnych dodatkowych logów, żadnej komunikacji serwerowej - tylko przechowanie informacji, którą i tak już jako użytkownik widzieliśmy. 

W zgłoszeniu napisałem, że warto przechwycić i przechować także inne notyfikacje ale tylko dlatego aby zachowanie aplikacji było jednolite.

Gdy myślę o sobie to rzeczywiście nie wydaje mi się to potrzebne, mam jednak kontakt z osobami naprawdę rozgarniętymi, które nie potrafią się wstrzelić w konwencję `Aplikacji` jaka dla mnie jest normą i np. nie rozumieją różnicy między notyfikacjami tygodniowymi a jakimikolwiek innymi. Cytuję: `Skoro aplikacja ma działać przez cały czas to po co mi jakieś powiadomienie, że działa?`

I jeszcze raz o tym: `jeśli dnia X pokazało się powiadomienie, które wykryło kontakt 14 dni temu to dnia X+1 ryzyko jest już nieaktualne` wg mnie jest to dziura warta załatania - można, np. ukryć powiadomienie

**Comment by Grze-Wo** [comment]
Obecne zmiany w aplikacji są zgodne z tym czego oczekiwałem - można podejrzeć nawet więcej informacji, niż proponowałem. Nawet jeśli błąd z notyfikacją nadal występuje to przestał być tak bardzo uciążliwy i to zgłoszenie możemy uznać za zamknięte.
