### ISSUE TITLE
Poviat ????

### ISSUE THREAD

**Issue by ledvor** [ProteGO-Safe/android#157]
**Describe the bug**
w opisie 4.6.0 użyto słowa poviat. Nie ma takiego słowa w języku angielskim.

A powiat (pronounced [ˈpɔvʲjat]; Polish plural: powiaty) is the second-level unit of local government and administration in Poland, equivalent to a county, district or prefecture (LAU-1, formerly NUTS-4) in other countries. The term "powiat" is most often translated into English as "county" or "district".

**To Reproduce**

**Current behavior**
A clear and concise description of what is happening right now.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device model: [e.g. SAMSUNG GALAXY S10E SM-G970]
 - OS: [e.g. Android 10.0]

**Additional context**

**Comment by TomaszMolenda** [comment]
Nie znam genezy postania tego fragmentu kodu ale stosowane nazewnictwo leży po stronie zespołu, może biznes w ten sposób rozmawia?
Jeżeli uważasz że w kodzie użyto nieprawidłowej nazwy zrób PR - jeżeli masz rację i PR bedzie ok pewnie wejdzie.
PS. Wymyślenie nazwy zawsze jest najtrudniejsze :)

**Comment by olekstomek** [comment]
Myślałem że taka nazwa jest użyta jako zmienna na backendzie więc ma to małe znaczenie. [Ale "poviat" jest używane na froncie](https://github.com/ProteGO-Safe/android/blob/25842573f81ae3535b77e1f8048c20e3b3482385/app/src/main/res/values-en/strings.xml) czyli jest to bezpośrednia informacja dla usera. Więc jednak rozważyłbym co dla anglojęzycznych użytkowników jest jaśniejsze i czy "poviat" to nie spolszczenie. ;)
![poviat_translate](https://user-images.githubusercontent.com/26818304/97280190-3ae32080-183c-11eb-9046-9296269f0faf.gif)

**Comment by TomaszMolenda** [comment]
Masz racje. To nie jest dla deweloperów :)
Wrzuciłem zadanie do backlogu - wewnętrzy numer SCPSU-384

**Comment by wojciechrak** [comment]
Anglistykiem nie jestem, ale wydaję się, że najbliższym odpowiednikiem w j. angielskim będzie `county`.
Patrz: https://en.wikipedia.org/wiki/Piaseczno_County

**Comment by krystian3w** [comment]
Tłumaczenia niby zatwierdzają tłumacze przysięgli.

**Comment by kamilgthecoders** [comment]
@krystian3w to prawda, przekazałem temat tłumaczowi, czekam na jego odpowiedź.

**Comment by kamilgthecoders** [comment]
Odpowiedź eksperta/tłumacza:

> Obecnie nie ma jednej ustalonej konwencji tłumaczenia terminów administracyjnych - w obiegu funkcjonuje kilka terminów: "powiat/poviat", "county" oraz "district", więc pozostaje dobrać je odpowiednio do okoliczności danego tłumaczenia.
> 
> Unikałbym słowa "county" czy "district". Zakładam, że skoro anglojęzyczna wersja aplikacji jest przeznaczona dla obcokrajowców mieszkających/przebywających w Polsce, to lepiej podsunąć im termin, który będzie tożsamy z tym, który funkcjonuje w języku polskim i z którym się mogą zetknąć na co dzień w mediach czy chociażby dokumentach administracyjnych, formularzach, generalnie w życiu codziennym.
> 
> Zaoszczędzimy mu wtedy wątpliwości czy "district/county" to na pewno "powiat" a nie jakaś inna jednostka administracyjna. Niby jest to oczywiste/łatwo się domyśleć, ale z powodu tego, że nie ma jednej konwencji, to np. na anglojęzycznych wersjach stron internetowych jednostek samorządowych pojawiają się różne wersje. Myślę, że stosowania "poviat/powiat" po prostu ułatwi orientację użytkownikom niepolskojęzycznym.

**Comment by olekstomek** [comment]
Ewentualnie można wybrać jeszcze taką drogę że będą uwzględnione uwagi wszystkich - przy słowie "poviat" można dać "i" (informacja) w indeksie górnym tak jak w ankiecie w checklistach gdzie po kliknięciu pojawia się okno z opisem i szczegółami co to oznacza. 

Wydaje się że można temat zamknąć.

**Comment by qLb** [comment]
Dziekuje za zgloszenie i wyczerpujaca odpowiedz, jednoczesnie uznaje ten issue za rozwiazany.
