### ISSUE TITLE
Brak informacji o pierwszej dawce szczepionki w województwach i zaszczepionych ogółem w poszczególnych województwach i powiatach

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/android#173]
Brak informacji o pierwszej dawce szczepionki w województwach i zaszczepionych ogółem w poszczególnych województwach i powiatach - puste miejsca. 
![1620679375229](https://user-images.githubusercontent.com/26818304/117723422-a5f5b280-b1e2-11eb-9679-92ff1b43ab1c.jpg)
![1620679375232](https://user-images.githubusercontent.com/26818304/117723453-af7f1a80-b1e2-11eb-8c90-2a275f6e19b2.jpg)
![1620679375225](https://user-images.githubusercontent.com/26818304/117723489-b7d75580-b1e2-11eb-9674-5f48a7425d2f.jpg)

Możliwe że wpływ ma na to [backend](https://github.com/ProteGO-Safe/backend).

**Comment by TomaszMolenda** [comment]
Wdrożone w https://github.com/ProteGO-Safe/backend/releases/tag/4.4.10-hotfix
