### ISSUE TITLE
Aplikacja powinna weryfikować certyfikat SSL serwera do którego się podłącza

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/android#18]

**Comment by mimi89999** [comment]
Pewnie możnaby też rozważyć certificate pinning.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
