### ISSUE TITLE
Aplikacja rozgłasza się, łączy z urządzeniami w pobliżu przez Bluetooth i pobiera ich identyfikatory

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/android#4]
Wymagania:
Działa na iOS i Android. Obie platformy widzą się nawzajem.
Maksymalnie oszczędza baterię.
Zapisujemy siłę sygnału
Działa w tle. Po zamknięciu aplikacja wybudza się automatycznie.
Co godzinę rozgłaszamy inny identyfikator.
Wykryte urządzenia możemy śledzić np. w BugFender

**Comment by OKatrych** [comment]
Proszę zobaczyć rozwiązanie naszej firmy https://medium.com/sigma-connectivity/protection-from-coronavirus-silent-carriers-5dcae266b302
Może się przydać.

**Comment by Cierpliwy** [comment]
Dzięki za link. W najbliższych dniach postaram się opisać aktualny mechanizm rozsyłania Beacon ID po BLE wraz z wszystkimi wnioskami i ograniczeniami (iOS/Android), które zostały wychwycone podczas testów. Myślę, że w ten sposób łatwiej będzie przeprowadzić dyskusję.

**Comment by Cierpliwy** [comment]
@OKatrych Tutaj jest krótki dokument z opisujący aktualne podejście + zestaw uwag, które zebraliśmy podczas testów. https://github.com/ProteGO-app/specs/pull/32

**Comment by marcinsowapoland** [comment]
Czy łączenie się aplikacji z urządzeniami nie będzie problematyczne? Czy nie boicie się o zużycie energii na te połączenia? Android ma ograniczoną liczbę urządzeń z którymi może jednocześnie się łączyć? Co gdy użytkownik wejdzie w tłum ludzi? Dacie radę "obskoczyć" wszystkie urządzenia? Czy fakt, że telefon użytkownika łączy się z innymi telefonami, nie będzie budził zastrzeżeń. Skanowanie i czytanie beaconów to raczej nie problem, ale te połączenia to trochę może być problem.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
