### ISSUE TITLE
Aplikacja daje możliwość ponownego przesłania kodu weryfikującego numer telefonu

### ISSUE THREAD

**Issue by bladekp** [ProteGO-Safe/android#52]
**Opis prozypozycji rozwiązania**

Obecnie po przesłaniu numeru telefonu użytkownik jest przenoszony do `registration_confirmation_view` z prośbą o wpisanie kodu potwierdzającego numer telefonu. W tym widoku użytkownik powinien mieć możliwość poproszenia o ponowne przesłanie kodu. Kod mógł nie zostać dostarczony z różnych przyczyn, użytkownik mógł omyłkowo usunąć SMS z kodem itp.

**Opis alternatywnych rozwiązań**

Alternatywnie można dać użytkownikowi możliwość powrotu do `registration_view`, tak żeby mógł jeszcze raz mógł użyć przycisku `DOŁĄCZ DO`, co prawda można to teraz zrobić przy pomocy sprzętowego przycisku powrotu, ale nie dla każdego może to być intuicyjne. Mógłby zatem istnieć drugi przycisk na `registration_confirmation_view` o tytule `POWRÓT`.

**Comment by jakublipinski** [comment]
To musi być zgodne z: https://github.com/ProteGO-app/backend/blob/master/sms_registration.md

**Comment by jakublipinski** [comment]
W design'ach jest przycisk "back" który powinien być widoczny na tym ekranie

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
