### ISSUE TITLE
Rozszerzenie mechanizmu sprawdzającego połączenie internetowe.

### ISSUE THREAD

**Issue by pawelByszewski** [ProteGO-Safe/android#56]
Sprawdzanie połączenie internetowego nie powinno się ograniczać jedynie do sprawdzenia statusu WIFI lub danych komórkowych ale powinno nastąpić sprawdzenie połączenia z jakims publicznym serwerem.

**Comment by mzgreen** [comment]
A może nawet z serwerem ProteGO?

**Comment by mikolak** [comment]
@mzgreen nie wiem czy to dobry pomysł - jeśli coś jest nie tak z naszym serwerem i nie uda się z nim nawiązać połączenia, to pokażemy błąd o braku internetu, co nie musi być prawdą. 
Problem jest taki, że nie wiem z jakim serwerem powinniśmy i może ta obawa jest nieuzasadniona. 

Nie powinniśmy używać pinga, bo routery mogą mieć domyślnie ustawioną blokowanie go (np. mój domowy router nie daje mi pingnąć DNS google, bo nie).

**Comment by jakublipinski** [comment]
Uprośćmy to. Jeśli `get_status` zwrócił błąd to pokazujemy okno `No Internet`. Zmienimy teksty tak aby mówiły o tym, że nie można połączyć się z serwerem ProteGO.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
