### ISSUE TITLE
Automatyczne wpisywanie kodu z SMS

### ISSUE THREAD

**Issue by shymmq** [ProteGO-Safe/android#60]
**Opis prozypozycji rozwiązania**

Kiedy pojawia się pole wpisywania kodu do rejestracji, aplikacja powinna nasłuchiwać przychodzących wiadomości SMS. Po otrzymaniu kodu aplikacja powinna automatycznie rejestrować użytkownika.

**Opis alternatywnych rozwiązań**

Użytkownik powinien mieć zawsze możliwość wpisania kodu ręcznie.

**Comment by mzgreen** [comment]
https://developers.google.com/identity/sms-retriever/overview

**Comment by shymmq** [comment]
@mzgreen orientujesz się jakie są minimalne wersje Play Services i poziom API do tej biblioteki? Nigdzie nie mogę tego znaleźć.

**Comment by mzgreen** [comment]
Tutaj https://developers.google.com/identity/sms-retriever/request#prerequisites jest minimalna wersja Play Services czyli 10.2, ale dalej w opisie są rzeczy które dochodziły w nowszych wersjach.
A tutaj https://android-developers.googleblog.com/2018/12/google-play-services-discontinuing.html?m=1 jest info, że Play Services nowsze niż 14.7.99 nie będą działać na ICS i niższych wersjach Androida. ProteGo ma target sdk 23 więc nie ma problemu.
Nie wiem na ile to odpowiada na Twoje pytanie :slightly_smiling_face:

**Comment by shymmq** [comment]
To dobrze, wydawało mi się że to działa tylko na najnowszych API. Swoją drogą dosyć wysoki ten minSdk, jak na aplikację która ma być docelowo dla każdego obywatela.

**Comment by mzgreen** [comment]
Bluetooth na Androidzie słynie z niestabilności i innych problemów, zwłaszcza na starszych wersjach systemu, więc jeśli bym miał zgadywać to postawiłbym na ten powód. Ale tak naprawdę to nie wiem co było brane pod uwagę wybierając minsdk. Może @pawelByszewski będzie wiedział?

**Comment by revenpl** [comment]
Czy backend wie, że powinien wysyłać SMS-y z kodem w odpowiednim formacie wraz z poniższym hashem? I kto może backendowi ten hash dostarczyć? 
https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string

**Comment by mikolak** [comment]
@DariuszAniszewski mógłbyś spojrzeć na ten format wiadomości do kojarzenia SMSów z naszą aplikacją?

**Comment by revenpl** [comment]
@jakublipinski @pawelByszewski @mikolak to ja mogę wziąć tego taska :)

**Comment by pawelByszewski** [comment]
@revenpl w idealnym scenariuszu, możemy poczekać na odpowiedź zespołu zajmującego się serwerem. Jakby co to wszystkie taski oznaczone `good first issue` tylko czekają aby je chwycić.

**Comment by revenpl** [comment]
@pawelByszewski @mikolak wystarczy, że w wiadomości sms w którymkolwiek miejscu znajdzie się hash:
F1jJRAje4UQ 
Mam nadzieję, że to nie będzie problem dla backendu :) Kod sms sparsuję sobie bez względu na treść samej wiadomości. Pytanie czy po otrzymaniu kodu sms i wstawieniu go do odpowiedniego pola od razu przechodzimy dalej czy czekamy na dodatkowe potwierdzenie od użytkownika?

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
