### ISSUE TITLE
Brak mozliwosci dodania zagranicznego numeru telefonu

### ISSUE THREAD

**Issue by przem123** [ProteGO-Safe/android#64]
Na ekranie powitalnym istnieje tylko mozliwosc dodania polskiego numeru z prefiksem +48. Czy na razie zagraniczne numery nie sa mozliwe ?

**Comment by jakublipinski** [comment]
Ze względu na to, że numer telefonu nie będzie obowiązkowy (https://github.com/ProteGO-app/specs/issues/34#issuecomment-609993832) użytkownicy mogą zarejestrować się bez nr telefonu.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
