### ISSUE TITLE
Statyczna weryfikacja zależności

### ISSUE THREAD

**Issue by maciekjanusz** [ProteGO-Safe/android#67]
**Opis prozypozycji rozwiązania**

Obecnie projekt korzysta z zależności pobieranych ad-hoc z zewnętrzych repozytoriów maven, bez sprawdzania sum kontrolnych co w skrajnych przypadkach może być luką bezpieczeństwa (patrz https://github.com/signalapp/gradle-witness#dependency-problems)
rozwiązaniem będzie użycie https://github.com/signalapp/gradle-witness w celu statycznej weryfikacji zależności

**Comment by koral--** [comment]
Czy wbudowane w gradle mechanizmy nie rozwiązują tego problemu? https://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by maciekjanusz** [comment]
@koral-- owszem, wymaga to podbicia wersji Gradle, ale dokumentacja nadal wskazuje na to, że jest to `incubating feature`, nie wiem co to oznacza w kontekście 'na ile można na tym polegać'. W każdym razie to też wygląda na rozwiązanie

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.

**Comment by koral--** [comment]
@jakublipinski nie widzę żeby coś się ruszyło w tej sprawie więc issue można spokojnie ponownie otworzyć
