### ISSUE TITLE
Aplikacja wyświetla powitanie

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/android#7]
**Pierwsze uruchomienie**
W przypadku kiedy aplikacja uruchamiana jest po raz pierwszy (nie mamy `user_id`), następuje rejestracja aplikacji. Użytkownikowi pokazywane są ekrany startowe:

**Powitanie w aplikacji**
Akceptacja regulaminu. Regulamin jako link otwierany w przeglądarce.
Wyjaśnienie jak działa aplikacja (może być kilka ekranów)
Prośba o włączenie Bluetooth. Aplikacja nie przechodzi dalej bez włączenia Bluetooth (chyba że nie da się skutecznie sprawdzić stanu Bluetooth, wtedy przechodzi).

**Comment by jakublipinski** [comment]
Możemy to zamknąć?

**Comment by mikolak** [comment]
Brakuje regulaminu i sprawdzenia stanu BT.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
