### ISSUE TITLE
Aplikacja powinna działać na możliwie niskiej wersji androida

### ISSUE THREAD

**Issue by tygrysio** [ProteGO-Safe/android#75]
Aplikacja powinna być powszechnie dostępna, także na stare urządzenia.
Udało mi się skompilować na minSdkVersion 21 a chciałbym od 17 bo takie mam urządzenie HTC ONE X+
Niżej w tej chwili się nie da - ograniczeniem jest com.polidea.cockpit:cockpit:3.1.2

**Comment by jakublipinski** [comment]
@tygrysio dzięki, wydaje mi się że Cockpit [używany jest tylko w wersji debug](https://github.com/ProteGO-app/specs/blob/master/specs/app_versions.md#android). Sprawdzisz w wersji release/production?

**Comment by tygrysio** [comment]
W wersji release uruchomiłem na minSdkVersion 17. Aplikacja się zatrzymała po podani nr telefonu i naciśnieciu wyślij kod. "Niestety, aplikacja ProteGo zaostała zatrzymana"

**Comment by mikolak** [comment]
Nie jestem pewien jakie są powody dla tak wysokiego minSDK w projekcie, ale 17 na pewno nie będziemy obsługiwać - obsługa BLE, która jest podstawą aplikacji, została wprowadzona w API 18.

**Comment by matsobdev** [comment]
> Nie wiem jakie są powody dla tak wysokiego minSDK w projekcie, ale 17 na pewno nie będziemy obsługiwać - obsługa BLE, która jest podstawą aplikacji, została wprowadzona w API 18.

API 18 tylko dla odbierania pakietów, a API 21 dla ich nadawania jak i odbierania (uwzględniając, że chipset fizycznie ma taką możliwość - raczej przed Lolipopem nikt takich nie instalował na pokładzie a i tak znajdują się też telefony, nie mogące nadawać, które pierwotnie wyszły na przykład na Androidzie M. Dla przykładu Huawei Y6 2017). Domyślam się, że COVID-19 API po stronie Androida będzie rozgraniczone dla 18 - 20, żeby chociaż mogły te telefony odbierać i dla 21+ - pełna funkcjonalność albo będzie to jedna metoda, żeby nie komplikować pisania apek a wszystko będzie się działo za kurtyną API.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
