### ISSUE TITLE
Aplikacja sprawdza wersję i ew. prosi o aktualizację

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/android#8]
Po uruchomieniu, aplikacja sprawdza czy zainstalowana wersja jest najnowsza i w przeciwnym wypadku Użytkownik proszony jest o zainstalowanie nowszej wersji i przekierowany jest do odpowiedniego sklepu z aplikacjami.

**Comment by mzgreen** [comment]
Polecam użycie https://developer.android.com/guide/playcore/in-app-updates

**Comment by Ruszkomak** [comment]
@jakublipinski  @pawelByszewski @mikolak Chętinie zajmę się tym zagadnieniem, czy jest wolne?

**Comment by mikolak** [comment]
Tak, jest wolne. Bierz śmiało.

**Comment by Ruszkomak** [comment]
Ok, biorę.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
