### ISSUE TITLE
Stare wersje zależności

### ISSUE THREAD

**Issue by koral--** [ProteGO-Safe/android#84]
Projekt używa np. Gradle 5.4.1 sprzed prawie roku, po którym wyszło kilkanaście stabilnych wersji.
Android Gradle plugin jest sprzed paru miesięcy.

Jest jakaś polityka, wymaganie biznesowe albo jakaś inna zależność która wymusza określone wersje bibliotek? Czy można śmiało zakładać PR z podbiciem wersji do nowszych stabilnych? Wolę się spytać najpierw niż ew. tracić czas na zmiany, które będą odrzucone.

**Comment by mikolak** [comment]
Można śmiało podbijać.

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
