### ISSUE TITLE
Przeniesienie logiki sprawdzania dostępności internetu do BaseViewModel

### ISSUE THREAD

**Issue by mikolak** [ProteGO-Safe/android#94]
Zadanie wyniesione z tego komentarza: https://github.com/ProteGO-app/android/pull/55#discussion_r405100496
do tego PR: https://github.com/ProteGO-app/android/pull/55

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
