### ISSUE TITLE
Możliwość powrotu do poprzednich ekranów z ekranu statusu użytkownika

### ISSUE THREAD

**Issue by tomaszmnich** [ProteGO-Safe/android#97]
**Opis błędu**

Użytkownik ma możliwość powrotu za pomocą przycisku BACK z ekranu głównego aplikacji (ekran ze statusem użytkownika) do poprzednich ekranów (onboarding). Błąd występuje przy pierwszym uruchomieniu aplikacji.

**Kroki**

1. Otwórz aplikację
2. Przejdź onboarding
3. Przejdź do ekranu głównego
4. Użyj przycisku BACK

**Oczekiwany zachowanie aplikacji**

Użytkownik nie powinien mieć możliwości powrotu do ekranu onboardingu z ekranu głównego

**Urządzenie (proszę wypełnij poniższe informacje dotyczące urządzenia):**
 - Nazwa: Samsung Galaxy S6
 - System operacyjny: Android
 - Wersja systemu operacyjnego: 7.0
 - Wersja aplikacji: ProteGO Stg 1.0.10-stg

 **Środowisko**
 - Wersja środowiska: stag

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
