### ISSUE TITLE
Brak walidacji poprawności kodu SMS

### ISSUE THREAD

**Issue by tomaszmnich** [ProteGO-Safe/android#98]
**Opis błędu**

Przycisk potwierdzenia kodu SMS jest niezablokowany jeżeli nie wpisze się 6 cyfr. Można potwierdzić niepoprawny kod SMS (kod SMS o niepoprawnym formacie).

**Kroki**

1. Wpisz nr telefonu
2. Przejdź do ekranu z kodem SMS
3. Wpisz niepoprawny format kodu SMS (mniej lub więcej niż 6 cyfr)
4. Potwierdź kod SMS

**Oczekiwany zachowanie aplikacji**

1. Walidacja poprawności kodu SMS powinna działać
2. Przycisk potwierdzenia kodu SMS powinien być zablokowany przy wpisanym niepoprawnym kodzie SMS (niepoprawny format)

**Urządzenie (proszę wypełnij poniższe informacje dotyczące urządzenia):**
 - Nazwa: Samsung Galaxy S6
 - System operacyjny: Android
 - Wersja systemu operacyjnego: 7.0
 - Wersja aplikacji ProteGO Stg 1.0.10-stg

 **Środowisko**
 - Wersja środowiska: stag

**Comment by jakublipinski** [comment]
Na [prośbę](https://github.com/ProteGO-Safe/specs/issues/104) @MateuszRomanow zamykam issues'y związane z wersją `1.0`. Jeśli ten temat dotyczy również aktualnej wersji, proszę o otwarcie.
